### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by jenvigo** [davidbailey00/deno-babel-demo#7]
```
/usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js run demo --scripts-prepend-node-path=auto

> demo
> deno -A loader.js ./demos/babel

sh: 1: deno: not found

```

**Comment by vtenfys** [comment]
You need to install Deno for this demo. Find out more about Deno: https://deno.land/

Furthermore, I haven't touched this in a long time so it's probably not useful anymore.

Deno now provides a Node.js compatibility mode: https://deno.land/manual@v1.19.0/npm_nodejs/compatibility_mode
